name: GitHub Book Publisher
run-name: ${{ github.actor }} is publishing using GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: sudo apt-get install pandoc
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to build your book."
      - name: Run pandoc to convert markdown to ePub
        run: cd ebooks && pandoc ../wisdom.md -o wisdom.epub
      - uses: EndBug/add-and-commit@v9
        with:
          message: 'Adding the new wisdom book'
          committer_name: GitHub Actions
          committer_email: actions@github.com
          add: 'ebook/wisdom.epub --force'
      - run: echo "🍏 This job's status is ${{ job.status }}."
